image: mcr.microsoft.com/dotnet/sdk:8.0

stages:
  - build
  - test

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH

build:
  stage: build
  script:
    - dotnet restore
    - dotnet build --no-restore --configuration Release -p:TreatWarningsAsErrors=true

test:
  stage: test
  needs: [build]
  script:
    - dotnet test --no-build --configuration Release --verbosity normal
